developer/yk-deploy.sh

Fixes https://github.com/G-Research/yunikorn-history-server/issues/8

Fix linux/amd64 support for YK deploy script.

---

developer/README.md
developer/yk-deploy.sh

Fixes https://github.com/G-Research/yunikorn-history-server/issues/11

Edit deployment YAML files in yunikorn-k8shim repo before building.

---

.github/workflows/ci.yml
Dockerfile
Makefile

This PR adds steps that build docker images for amd64 and arm64.
Fixes: https://github.com/G-Research/gr-oss/issues/723

Add build docker images

---

cmd/event-collector/main.go
internal/webservice/webservice.go
internal/ykclient/api_handlers.go
internal/ykclient/client.go
internal/ykclient/eventhandler.go
log/logger.go

Update print statement with log statement.

---

.gitignore
cmd/yunikorn-history-server/commands/root.go
internal/config/config.go
internal/webservice/routes.go
internal/webservice/webservice.go

Closes https://github.com/G-Research/yunikorn-history-server/issues/85

feat: add support for serving static files

---

.github/workflows/ci.yml

Closes https://github.com/G-Research/yunikorn-history-server/issues/92

fix: wrong path when uploading docker tarball artifacts

---

migrations/20240628155246_init-tables.up.sql

Fixes https://github.com/G-Research/yunikorn-history-server/issues/44

Change applications.reservations column type to JSONB

---

build/yunikorn-history-server/Dockerfile

Closes https://github.com/G-Research/yunikorn-history-server/issues/102

fix: bad docker entrypoint

---

test/e2e/e2e_test.go

Closes #81 
I am experiencing an issue where this particular test fails when I run the entire suite of end-to-end (E2E) tests. Interestingly, all the E2E tests fail in this scenario. However, if I run only this specific test, it passes without any problems. I have been unable to identify a specific cause for this discrepancy.
We use the `ws/v1/partition/default/queue/root.%s/applications` endpoint to retrieve the list of applications. This endpoint can take a considerable amount of time to update, so I have set the timeout to 500 seconds. The issue might be related to this extended timeout.
**I would appreciate any feedback or insights into this problem.**

E2E Test for App creation

---

internal/yunikorn/sync.go
internal/yunikorn/sync_test.go

Add partition names to children queues

---

.dockerignore
Makefile
build/yunikorn-history-server/Dockerfile
internal/webservice/routes.go
web/package-lock.json
web/yarn.lock

CHANGELOG
* Improve `make web-build` target to install Angular CLI and run npm install also
* Change static routes endpoint from /static to /web
* Add multi-stage docker build where builder transpiler web into assets folder
* Add .dockerignore to reduce files copied to Docker context

feat: bundle web into docker build stage and minor cosmetics along it

---

internal/database/repository/mock_repository.go
internal/database/repository/queue.go
internal/database/repository/queue_int_test.go
internal/database/repository/repository.go
internal/model/models.go

Implement delete queue repository method.

---

.github/workflows/check-required.yml

This PR replaces the check required script with a common action

Add check required action in place of the script

---

Makefile
build/yunikorn-history-server/Dockerfile

Use build arg for base image version

---

internal/database/repository/application_int_test.go

Replace UpsertQueues to AddQueues in integration test

---

internal/database/repository/mock_repository.go

Re-generate code to prepare for #95

Update generated code from `make codegen`

---

config/yunikorn-history-server/config.yml
config/yunikorn-history-server/local.yml
go.mod
go.sum
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/config.yml
internal/webservice/routes.go
internal/webservice/webservice.go

closes #196
Also done following manual testing
The browser rejects the response and gives a CORS error in the console.
The browser accepts the response and successfully displays the webpage.

Add CORS middleware

---

internal/webservice/routes.go

Add docs for `getAppsPerPartitionPerQueue` method

docs: document getAppsPerPartitionPerQueue method

---

.github/actions/setup-go/action.yml
.github/workflows/ci.yml

Add codegen job to check that generated code is up-to-date

---

internal/database/repository/mock_repository.go
internal/database/repository/queue.go
internal/database/repository/queue_int_test.go
internal/database/repository/repository.go

Implement UpdateQueue() repo method.

---

Makefile

replace echo statement

---

Makefile

Include removal of yhs local for development

Add helm uninstall yhs local

---

go.mod
go.sum
internal/database/repository/mock_repository.go
internal/database/repository/node.go
internal/database/repository/repository.go
internal/yunikorn/sync.go

use ulid for uuid in node_utilization to support time based ordering

---

Makefile
build/yunikorn-history-server/Dockerfile
web/angular.json
web/package.json
web/yarn.lock

Updated versions to match YuniKorn Web `master` branch

Versions update to match YuniKorn Web

---

internal/webservice/helpers.go
internal/webservice/helpers_test.go

fix nil slice when no group parameter in the URL query

---

internal/database/repository/application.go
internal/database/repository/history.go
internal/database/repository/node.go
internal/database/repository/partitions.go
internal/database/repository/queue.go
migrations/20240628155246_init-tables.up.sql

replace uuid with ulid

---

internal/database/repository/history.go
internal/database/repository/history_int_test.go
internal/database/repository/mock_repository.go
internal/database/repository/repository.go
internal/webservice/helpers.go
internal/webservice/helpers_test.go
internal/webservice/routes.go

pagination and filters in app history endpoints

---

Makefile
web/package-lock.json
web/src/app/models/envconfig.model.ts
web/src/app/services/envconfig/envconfig.service.ts
web/src/app/services/scheduler/scheduler.service.ts
web/src/environments/environment.template.ts
web/src/environments/environment.ts
web/src/environments/setEnvironmentVariables.ts
web/yarn.lock

This pull request includes several changes to the Makefile and web application configuration to support new environment variables and streamline the build process. The most important changes include modifications to the Makefile to add new environment variables, updates to the web application configuration files to support these variables, and improvements to the `EnvConfigService` class to handle the new URLs.
Modified the `web-build` target to include `yhsApiURL` and `yunikornApiURL` environment variables during the build process.
* Added optional `yunikornApiURL` and `yhsApiURL` properties to the `EnvConfig` interface.
* Added `yunikornApiURL` and `yhsApiURL` properties to the environment configuration templates. 
* Updated the script to conditionally write to the production …

Implemented ENV parametrization in YHS Web

---

internal/database/repository/mock_repository.go
internal/database/repository/node.go
internal/database/repository/node_int_test.go
internal/database/repository/repository.go
internal/webservice/helpers.go
internal/webservice/routes.go

implement pagination and filters to nodes endpoint

---

internal/database/repository/mock_repository.go
internal/database/repository/node.go
internal/database/repository/node_init_test.go
internal/database/repository/repository.go
internal/webservice/helpers.go
internal/webservice/routes.go

implement pagination and filters to nodeutilizations endpoint

---

internal/database/repository/application.go
internal/database/repository/application_int_test.go
internal/database/repository/mock_repository.go
internal/database/repository/node.go
internal/database/repository/partitions.go
internal/database/repository/queue.go
internal/database/repository/repository.go
internal/model/application.go
internal/model/application_test.go
internal/model/models.go
internal/yunikorn/event_handler.go
internal/yunikorn/sync.go
internal/yunikorn/sync_int_test.go
migrations/20240628155246_init-tables.up.sql

Application sync

---

README.md

Add note to refer the fork repositories.

---

internal/webservice/routes.go

Add swagger specification for API params.

---

go.mod
go.sum
internal/database/repository/application.go
internal/database/repository/application_int_test.go
internal/database/repository/mock_repository.go
internal/database/repository/repository.go
internal/model/application.go
internal/model/application_test.go
internal/model/models.go
internal/yunikorn/event_handler.go
internal/yunikorn/sync.go
internal/yunikorn/sync_int_test.go

This change marks the old applications as deleted and avoids fetching them from the db

Fix application checks with the new id field

---

internal/database/repository/mock_repository.go
internal/database/repository/node.go
internal/database/repository/node_int_test.go
internal/database/repository/repository.go
internal/model/node.go
internal/model/node_test.go
internal/webservice/routes.go
internal/yunikorn/event_handler.go
internal/yunikorn/service.go
internal/yunikorn/sync.go
internal/yunikorn/sync_int_test.go
migrations/20240628155246_init-tables.up.sql

Implement node event handler

---

internal/database/repository/mock_repository.go
internal/database/repository/queue.go
internal/database/repository/queue_int_test.go
internal/database/repository/repository.go
internal/yunikorn/event_handler.go
internal/yunikorn/sync.go

Bugfix in syncPartitionQueues() implementation 

---

Makefile

Change Makefile targets for running the Yunikorn services to make testing a separate UHS instance a bit easier. Developers can now use `make create-cluster` and `make delete-cluster`, to be consistent with Kind's `create-cluster` and `delete-cluster` commands.
Fixes https://github.com/G-Research/unicorn-history-server/issues/356

Clean up and make cluster Make targets consistent.

---

web/README.md
web/mock-server/db.json
web/mock-server/routes.json

This pull request includes updates to the mock server configuration and documentation to improve local development and testing. The most important changes include updating endpoint paths in the mock server and adding example endpoints to the README file.

Updated mock server responses

---

Makefile

closes #373 
Tasks
1. Remove migration execution from the integration-test command in the Makefile.
2. Ensure integration tests run smoothly without the migration step.
3. Use `uhs-test` cluster for tests.

Skip migration for integration test, update cluster name for tests

---

internal/database/repository/application_int_test.go

Increase integration test for applications repo methods.

---

internal/database/repository/partitions_init_test.go

Add missing integration test for partition repo methods.

---

web/package.json
web/pnpm-lock.yaml

Updated yunikorn-web dependency and regenerated lock file.

Updated yunikorn-web in package.json

---

.mergify.yml

add mergify rules.
