G-Research/unicorn-history-server

- internal/repository/application.go
- internal/ykclient/api_handlers.go
- internal/ykclient/client.go
- internal/ykclient/eventhandler.go
Part of: https://github.com/G-Research/gr-oss/issues/654
For events handling, we might need some refactoring to a different package away from the `ykclient` package. will keep it simple in this PR for now and refactor later.
I will update the mentioned issue of how the application will look like in our database eventually compared to how it looks liks from querying the scheduler API
> Implement events handler for events of type APP

- developer/yk-deploy.sh
It seems convenient to take the `base_dir` as cmd arg, rather than manually modifying the `yk-deploy.sh` if the base directory is different.
> Accept base directory of ynikorn repos as cmd argument.

- .github/workflows/check-required.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
This PR adds workflows for releasing built docker images for YHS, and a `check-required` workflow as in FML. There are a couple of prerequisites before merging this PR.
Prerequisites:
Fixes: https://github.com/G-Research/gr-oss/issues/729
> Add check-required workflow and release workflow

- Dockerfile
> Removes the copying of `yhs.yml` from the Dockerfile #32

- .github/workflows/ci.yml
- Makefile
This PR adds a job that runs go unit tests. Also, a linter flag that ignores lint errors is removed so now the job and workflow will fail if lint errors are found.
Working examples:
- [No lint errors all good and green](https://github.com/gr-oss-devops/yunikorn-history-server/actions/runs/9463353428)
- [Some lint errors, job failed](https://github.com/gr-oss-devops/yunikorn-history-server/actions/runs/9463494677/job/26068801697)
Fixes: https://github.com/G-Research/gr-oss/issues/733
> Add tests job and fail job if lint errors found

- .gitignore
- go.mod
- go.sum
- internal/webservice/webservice.go
- internal/ykclient/client.go
- log/logger.go
I reviewed the implementation of `zap` in the `ynikorn-core` repository. In this PR, I've included a trimmed-down version based on their approach. I would greatly appreciate your feedback to determine if this is something we can proceed with. 
Logs are saved into a file as well as into standard out.
**Tasks** 
**Output**
> Configure Zap logger

- cmd/event-collector/main.go
- cmd/event-collector/main_test.go
- yhs.yml
> Consistently process env vars and config parameter from yhs

- developer/README.md
- developer/yk-deploy.sh
As some developers in the SPARK team at G-R are using `minikube` to do Yunikorn development and testing, this PR adds support for using `minikube` in lieu of `kind` for running YHS. Also, some more info about tool requirements has been added to the `developer/README.md`.
Fixes https://github.com/G-Research/yunikorn-history-server/issues/47
> Add support for using minikube as K8S base, update README.

- charts/README.md
- charts/templates/configmap.yaml
- charts/values.yaml
- cmd/event-collector/main.go
- go.mod
- go.sum
- log/logger.go
- yhs.yml
> Configuration support for zap logger

- Makefile
- hack/run-tests.sh
- test/performance/README.md
- test/performance/event_handler_test.js
Related to #34
A load test was done on the cluster using [K6](https://grafana.com/docs/k6/latest/). A variable number of `VUs` are used to create a burst of events in the cluster. 
The number of `APP.ADD` events captured by YHS is counted.
Time: **15s, 5 virtual users (VUs)** for concurrent submission of pods in the cluster
Pod Submitted: 450
Event processed by YHS: 550
Time: **15s, 10 virtual users (VUs)** for concurrent submission of pods in the cluster
Pod Submitted: 690
Event processed by YHS: 790
Time: **15s, 10 virtual users (VUs)** for concurrent submission of pods in the cluster
Pod Submitted: 909
Event processed by YHS: 909
Time: **25s, 50 virtual users (VUs)** for concurrent submission of pods in the cluster
Pod Submitted: 4008
Event processed by YHS: 4108
> Performance testing using k6 for event handler

- internal/health/health_int_test.go
- internal/yunikorn/sync_int_test.go
Remove application history check - this is inherently a flaky test, due to Yunikorn having very variable processing time for application history data, so we cannot rely on it without having a very long timeout value.
Fix check for expected error message when we specify a bad health endpoint URL - Linux gives a different trailing message after the "lookup invalid-host" substring. This now passes on both MacOS and Linux systems.
Make check for getting parititons just log the error, and not be fatal.
Fixes https://github.com/G-Research/yunikorn-history-server/issues/97
> Integration test fixes

- .github/workflows/release.yml
Checks:
- Create GitHub app required for this process and pass the fingerprint of the created app via comment on this https://github.com/G-Research/charts/pull/132
- Create the environment `invoke-push` and add following secrets from created app
Goal of this PR is to use official process of publishing charts to G-Research repo https://g-research.github.io/charts/
> Publish chart to G-Research/charts repository

- test/e2e/e2e_test.go
Closes #80 
Implement an end-to-end test to verify that YHS can observe queue creation events in the `yunikorn` scheduler. Also, verify that the event is saved and the data is visible in the web service.
**Definition of Done (DoD)**
**Refactor**
**Notes**
Processing and returning the newly created queues by the web service takes considerable time. Therefore, the timeout is set to `400` seconds, making the process quite slow.
> Implement test to verify queue creation

- .github/workflows/release.yml
As discussed internally, proposed way to publish helm chart should be only when pushing tags starting with `refs/tags/v`
> publish helm chart only on tags

- Makefile
- test/performance/README.md
- test/performance/event_handler_test.js
> Generate HTML report for k6 performance test

- Makefile
- charts/yunikorn-history-server/templates/deployment.yaml
This PR fixs the failure by adopts CGO option when compiling and adds the command to the chart/template/deployment.yml. 
#165 
```
make kind-all
make kind-load-image
sed -i 's/tag: .*/tag: "<YOUR IMAGE TAG>"/g' charts/yunikorn-history-server/values.yaml
helm install yhs chart -n yunikorn
```
> [YHS-165] upadte build and add command in chart

- internal/database/repository/events.go
- internal/yunikorn/stream_test.go
For the InMemoryEventRepository.Counts() func, lock the internal mutex, then construct a copy of the event-counts map and return the copy - to avoid Golang "concurrent map read/write" panics.
Fixes https://github.com/G-Research/yunikorn-history-server/issues/171
> Event-Type Counts fix - lock event-counts mutex and return a map copy, to avoid panics

- internal/config/config.go
- internal/config/config_test.go
YAML format is structured, allowing multiple levels within an object. However, envs are flat (only one level).
This change ensures that yaml is flattened, so fetching environment variables is the same for both formats. It still allows multiple levels, but both of these will be accepted:
```yaml
yhs:
port: 8080
yhs_port: 8080
```
Fixes #204
> Flatten out the config to allow similar yaml and env fetching

- internal/webservice/routes.go
- internal/webservice/routes_test.go
- internal/webservice/testdir/index.html
- internal/webservice/testdir/js/app.js
SPA handler returns index.html if the file requested is not present, so it can leave routing to the UI framework.
Fixes #59
> Implement SPA handler to return ui on root path

- internal/yunikorn/sync_int_test.go
We are moving away form `sync` loop. Hence we do not need this test. 
closes #280
> Remove faulty integration test.

- internal/database/migrations/gomigrate_int_test.go
> Rewrite gomigrate test using testcontainer

- internal/webservice/response.go
- internal/webservice/routes.go
- internal/webservice/routes_test.go
- internal/yunikorn/sync.go
> Improve error response when resource is unavailable

- Makefile
The latest charts are not found at bitnami https://charts.bitnami.com/bitnami
Therefore, using the OCI registry which is the recommended way to install Bitmani charts. 
Ref: https://bitnami.com/stack/postgresql/helm
> use OCI registry for installing postgres for local dev.

- Makefile
- build/unicorn-history-server/Dockerfile
- web/package.json
Changes in this PR:
- The build process for the web is moved to Dockerfile.
- `make web-build` is kept for local development and testing.
- `make install-tools` will not install node dependencies, but if `make web-build` is run, node dependencies will be installed
> Migrated web build to Dockerfile
